# Generated by Django 4.1.13 on 2024-05-19 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campany_name', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('total_env_label', models.IntegerField(null=True)),
                ('total_soc_label', models.IntegerField(null=True)),
                ('total_gov_label', models.IntegerField(null=True)),
                ('total_env_neutral', models.IntegerField(null=True)),
                ('total_env_opportunity', models.IntegerField(null=True)),
                ('total_env_risk', models.IntegerField(null=True)),
                ('total_soc_neutral', models.IntegerField(null=True)),
                ('total_soc_opportunity', models.IntegerField(null=True)),
                ('total_soc_risk', models.IntegerField(null=True)),
                ('total_gov_neutral', models.IntegerField(null=True)),
                ('total_gov_opportunity', models.IntegerField(null=True)),
                ('total_gov_risk', models.IntegerField(null=True)),
                ('total_e_score', models.FloatField(null=True)),
                ('total_s_score', models.FloatField(null=True)),
                ('total_g_score', models.FloatField(null=True)),
                ('total_esg_score', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'db_table': 'campany',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CampanyDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factors', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=200, null=True)),
                ('score_class', models.FloatField(null=True)),
                ('sentiment', models.CharField(max_length=200, null=True)),
                ('score_sentiment', models.FloatField(null=True)),
                ('e_score', models.FloatField(null=True)),
                ('s_score', models.FloatField(null=True)),
                ('g_score', models.FloatField(null=True)),
                ('recommandation', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esganalyse.campany')),
            ],
            options={
                'db_table': 'campany_details',
            },
        ),
    ]
