# Generated by Django 4.1.13 on 2024-04-24 12:41

from django.db import migrations, models
import django.utils.timezone
import usermanagement.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True, validators=[usermanagement.functions.CustomValidator.validate_username])),
                ('password', models.CharField(max_length=200, unique=True, validators=[usermanagement.functions.CustomValidator.validate_password])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[usermanagement.functions.CustomValidator.validate_email])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
